........E......
======================================================================
ERROR: test_one_million (test_numbers.NumbersTest.test_one_million)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 87, in test_one_million
    result = Numbers().to_number(1000010)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 40, in to_number
    number_string = number_string + (self.get_number_by_order(number_part, order))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 59, in get_number_by_order
    second_digit=int(str(number)[1])
                     ~~~~~~~~~~~^^^
IndexError: string index out of range

----------------------------------------------------------------------
Ran 15 tests in 0.066s

FAILED (errors=1)
