EE.E..EE
======================================================================
ERROR: test_every_two_digit_number (test_numbers.NumbersTest.test_every_two_digit_number)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 46, in test_every_two_digit_number
    result = [Numbers().to_number(number) for number in range(10,100)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 18, in to_number
    return self.to_tens(first_digit, true) + self.to_units(second_digit)
                                     ^^^^
NameError: name 'true' is not defined. Did you mean: 'True'?

======================================================================
ERROR: test_ninety_nine (test_numbers.NumbersTest.test_ninety_nine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 42, in test_ninety_nine
    result = str(Numbers().to_number(99))
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 18, in to_number
    return self.to_tens(first_digit, true) + self.to_units(second_digit)
                                     ^^^^
NameError: name 'true' is not defined. Did you mean: 'True'?

======================================================================
ERROR: test_one_hundred (test_numbers.NumbersTest.test_one_hundred)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 50, in test_one_hundred
    result = Numbers().to_number(100)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 23, in to_number
    return self.to_hundreds(first_digit) + self.to_tens(second_digit, false) + self.to_units(third_digit)
                                                                      ^^^^^
NameError: name 'false' is not defined. Did you mean: 'False'?

======================================================================
ERROR: test_three_hundred (test_numbers.NumbersTest.test_three_hundred)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 54, in test_three_hundred
    result = Numbers().to_number(300)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 23, in to_number
    return self.to_hundreds(first_digit) + self.to_tens(second_digit, false) + self.to_units(third_digit)
                                                                      ^^^^^
NameError: name 'false' is not defined. Did you mean: 'False'?

======================================================================
ERROR: test_three_hundred_ten (test_numbers.NumbersTest.test_three_hundred_ten)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 58, in test_three_hundred_ten
    result = Numbers().to_number(310)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sandbox/numbers.py", line 23, in to_number
    return self.to_hundreds(first_digit) + self.to_tens(second_digit, false) + self.to_units(third_digit)
                                                                      ^^^^^
NameError: name 'false' is not defined. Did you mean: 'False'?

----------------------------------------------------------------------
Ran 8 tests in 0.039s

FAILED (errors=5)
